# Generated by Django 4.1.1 on 2023-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDRList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BDName', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('BloodGP', models.CharField(max_length=100)),
            ],
        ),
    ]
